---
- name: Deploy da Aplicação no Servidor Real
  hosts: servidores_web
  become: yes
  tasks:
    - name: 1. Garantir que a pasta da app existe
      file:
        path: /home/sre/projeto-app
        state: directory
        owner: sre
        group: sre
        mode: '0755'

    - name: 2. Sincronizar arquivos da pasta docker para o servidor
      copy:
        src: ../docker/
        dest: /home/sre/projeto-app/
        owner: sre
        group: sre

    - name: 3. Subir a aplicação com Docker Compose
      shell: "docker compose up -d --build"
      args:
        chdir: /home/sre/projeto-app
